### ISSUE TITLE
Hope you will give Taskade a try!

### ISSUE THREAD

**Issue by johnxie** [nikitavoloboev/my-ios#12]
Hope you will give Taskade a try!

We are on web, desktop, and mobile.

Our app lets you transform a task list into a kanban board, mind map, and more.

<img width="2065" alt="taskade-board" src="https://user-images.githubusercontent.com/792088/74992547-4359a080-53fd-11ea-8b79-ba3e43626213.png">

Below is our mobile app link. Thanks!

https://itunes.apple.com/us/story/id1433671795

**Comment by nikitavoloboev** [comment]
very happy with 2do :)
