### ISSUE TITLE
Airr- Podcasting notetaking app.

### ISSUE THREAD

**Issue by siddchauhan77** [nikitavoloboev/my-ios#15]
I came across your digital blog today and it has so many cool things in different areas. This is exactly how I want to present my own knowledge as a guide not an expert online. Thanks for sharing. 

Airr is only for ios right now but it allows you to take notes on certain segments of a podcast with one click and you can choose the duration of the clips recorded and adjust along with adding a caption on them. 

Extra meta mode - Use Airr to take notes on podcasts and then use Readwise.io to pull those notes into one place which then take them into Notion or Roam Research.

**Comment by nikitavoloboev** [comment]
It's a nice app, thanks. If I use it more over Overcast, I'll add it :)
