### ISSUE TITLE
Simon Tatham's Portable Puzzle Collection

### ISSUE THREAD

**Issue by madsen** [nikitavoloboev/my-ios#7]
[Simon Tatham's Portable Puzzle Collection](https://www.chiark.greenend.org.uk/~sgtatham/puzzles/) has an [iOS port](https://hewgill.com/puzzles/), and in my opinion it's the best puzzle app for iOS.

If you're familiar with the collection, the iOS port is exactly what you'd expect.  The graphics are minimal, and the sound consists of a click to let you know when your press has become a long press. But the advantages are:

- It's fast.  Go from clicking the icon to playing in about 0.5 sec.
- It's small. 3.7MB for app and data.
- There's a good selection of puzzle types.
- All puzzles have random level generators for effectively infinite replayability. 
- It's free. No ads or annoying splash screen.

I've tried a number of iOS puzzle games, and this is the only one that's stayed on my home screen for 5 years of almost daily use.  It's the perfect app to kill a couple minutes.

**Comment by nikitavoloboev** [comment]
Looks interesting, thanks.
